stages:
  - build
  - test
  - deploy

job-build:
  image: docker:latest
  stage: build
  script:
    - cd backend
    - docker build -t chouffe/haskell-bazaar:latest .
    # TODO: push?

job-test:
  image: tmaier/docker-compose:latest
  stage: test
  script:
    - cd backend
    - docker-compose up -d
    - docker container exec haskell-bazaar-api stack test

job-deploy:
  stage: deploy
  script:
    - cd backend
    - echo "Deploying..."
