image: docker:stable

variables:
   # When using dind service we need to instruct docker, to talk with the
   # daemon started inside of the service. The daemon is available with
   # a network connection instead of the default /var/run/docker.sock socket.
   #
   # The 'docker' hostname is the alias of the service container as described at
   # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
   #
   # Note that if you're using Kubernetes executor, the variable should be set to
   # tcp://localhost:2375 because of how Kubernetes executor connects services
   # to the job container
   DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

services:
   - docker:dind

cache:
  key: build-cache
  paths:
    - ./backend/.stack-work

stages:
  - build
  - test
  - deploy

before_script:
  - pwd
  - ls -larth
  - ls -larth ./backend/
  - docker info
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker image pull chouffe/haskell-bazaar:dev

build:
  stage: build
  script:
    - cd backend
    - docker image build --cache-from=fpco/stack-build:lts-9.21,chouffe/haskell-bazaar:dev -t chouffe/haskell-bazaar:dev -f Dockerfile.dev .
    - docker image push chouffe/haskell-bazaar:dev
    # TODO use cache layer here to pass on artifacts to next stages

test:
  image: tmaier/docker-compose:latest
  stage: test
  script:
    - cd backend
    - docker image build --cache-from=fpco/stack-build:lts-9.21,chouffe/haskell-bazaar:dev -t chouffe/haskell-bazaar:dev -f Dockerfile.dev .
    - docker-compose up -d
    - docker container exec haskell-bazaar-api stack test

deploy:
  stage: deploy
  script:
    - cd backend
    - docker image build --cache-from=fpco/stack-build:lts-9.21,chouffe/haskell-bazaar:dev -t chouffe/haskell-bazaar:dev -f Dockerfile.dev .
    - docker build -t chouffe/haskell-bazaar:latest -f Dockerfile .
    # TODO: use the sha short version here instead of latest
    - docker push chouffe/haskell-bazaar:latest
    - echo "Deploying..."
