# image: ubuntu:18.10

stages:
  - build
  - test
  - deploy

job-build:
  stage: build
  script:
    - cd backend
    - make build

job-test:
  stage: test
  script:
    - cd backend
    - docker-compose up -d
    - make test
  before_script:
    - curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose --version

job-deploy:
  stage: deploy
  script:
    - cd backend
    - echo "Deploying..."
