image: docker:stable

variables:
   # When using dind service we need to instruct docker, to talk with the
   # daemon started inside of the service. The daemon is available with
   # a network connection instead of the default /var/run/docker.sock socket.
   #
   # The 'docker' hostname is the alias of the service container as described at
   # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
   #
   # Note that if you're using Kubernetes executor, the variable should be set to
   # tcp://localhost:2375 because of how Kubernetes executor connects services
   # to the job container
   DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

services:
   - docker:dind

cache:
  key: build-cache
  paths:
    - backend/.stack-work

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    - cd backend
    - docker build -t chouffe/haskell-bazaar:latest .
    # TODO: push?

job-test:
  image: tmaier/docker-compose:latest
  stage: test
  script:
    - cd backend
    - docker-compose up -d
    - docker container exec haskell-bazaar-api stack test

job-deploy:
  stage: deploy
  script:
    - cd backend
    - echo "Deploying..."
