image: docker:stable

variables:
   # When using dind service we need to instruct docker, to talk with the
   # daemon started inside of the service. The daemon is available with
   # a network connection instead of the default /var/run/docker.sock socket.
   #
   # The 'docker' hostname is the alias of the service container as described at
   # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
   #
   # Note that if you're using Kubernetes executor, the variable should be set to
   # tcp://localhost:2375 because of how Kubernetes executor connects services
   # to the job container
   DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

services:
   - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin

build:
  stage: build
  script:
    - docker image pull chouffe/haskell-bazaar:dev
    - docker image build --cache-from=fpco/stack-build:lts-9.21,chouffe/haskell-bazaar:dev -t chouffe/haskell-bazaar:dev -f ./backend/Dockerfile.dev ./backend

test:
  stage: test
  script:
    - docker-compose up -d
    # Backend tests
    - docker container exec haskell-bazaar-api stack test
    # TODO: add frontend tests

deploy:
  stage: deploy
  script:
    - docker image build --cache-from=fpco/stack-build:lts-9.21,chouffe/haskell-bazaar:dev -t "chouffe/haskell-bazaar:$CI_COMMIT_SHA" -f ./backend/Dockerfile ./backend
    - echo "PUSHING TO REPOSITORY $CI_COMMIT_SHA"
    # - docker push "chouffe/haskell-bazaar:$CI_COMMIT_SHA"
