version: '3.4'

services:

  frontend:
    image: nginx:stable-alpine
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  frontend:
    container_name: haskell-bazaar-repl
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /clj/target
      - /clj/node_modules
      - /clj/resources/public/js/compiled
      - ./frontend:/clj
    networks:
      - backend
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1 3449"]

  nginx:
    image: nginx:stable-alpine
    networks:
      - frontend
      - backend
    links:
      - api
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    restart: always

  api:
    container_name: haskell-bazaar-api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - /opt/build/.stack-work
      - ./backend:/opt/build
    command: >
      sh -c "stack build &&
             stack exec haskell-bazaar-exe"
    environment:
      - ENVIRONMENT=Dev
    secrets:
      - mailchimp-api-key
      - mailchimp-base-url
      - mailchimp-list-id
      - psql-user
      - psql-password
      - psql-db

  postgres:
    image: postgres:11.1
    container_name: haskell-bazaar-postgres
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "haskellbazaar"]

    volumes:
      - psql-data:/var/lib/postgresql/data

      # Run init.sql and seed.sql on creation
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./db/scripts/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

    secrets:
      - psql-user
      - psql-password
      - psql-db

    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-password
      - POSTGRES_DB_FILE=/run/secrets/psql-db
      - POSTGRES_PORT=5432

volumes:
  psql-data:

secrets:

  # Postgresql
  psql-user:
    file: ./secrets/psql-user
  psql-password:
    file: ./secrets/psql-password
  psql-db:
    file: ./secrets/psql-db

  # Mailchimp
  mailchimp-api-key:
    file: ./secrets/mailchimp-api-key
  mailchimp-base-url:
    file: ./secrets/mailchimp-base-url
  mailchimp-list-id:
    file: ./secrets/mailchimp-list-id

networks:
  frontend:
  backend:
