version: '3.4'

services:

  web:
    container_name: haskell-bazaar-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - frontend
    ports:
      - "8002:8002"
    links:
      - postgres
    volumes:
      - /opt/build/.stack-work
      - .:/opt/build
    command: >
      sh -c "stack build &&
             stack exec haskell-bazaar-exe"
    environment:
      - ENVIRONMENT=Dev
    secrets:
      - mailchimp-api-key
      - mailchimp-base-url
      - mailchimp-list-id
      - psql-user
      - psql-password
      - psql-db

  postgres-backup:
    image: chouffe/haskell-bazaar-postgres-backup
    build:
      context: ./db/
      dockerfile: Dockerfile
    links:
      - postgres
    container_name: haskell-bazaar-postgres-backup
    networks:
      - frontend
    volumes:
      - psql-data:/var/lib/postgresql/data
      - psql-backups:/backups
      - ./db:/db
    secrets:
      - psql-user
      - psql-password
      - psql-db

  postgres:
    image: postgres:10.5
    container_name: haskell-bazaar-postgres
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "haskellbazaar"]

    volumes:
      - psql-data:/var/lib/postgresql/data

      # Run init.sql and seed.sql on creation
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./scripts/db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

    ports:
      - "5432:5432"

    secrets:
      - psql-user
      - psql-password
      - psql-db

    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-password
      - POSTGRES_DB_FILE=/run/secrets/psql-db
      - POSTGRES_PORT=5432

    # TODO: define network?

volumes:
  psql-data:
  psql-backups:

secrets:

  # Postgresql
  psql-user:
    file: ./secrets/psql-user
  psql-password:
    file: ./secrets/psql-password
  psql-db:
    file: ./secrets/psql-db

  # Mailchimp
  mailchimp-api-key:
    file: ./secrets/mailchimp-api-key
  mailchimp-base-url:
    file: ./secrets/mailchimp-base-url
  mailchimp-list-id:
    file: ./secrets/mailchimp-list-id

networks:
  frontend:
