version: '3'

services:
  # web:
  #   image: haskell-bazaar-server
  #   container_name: haskell-bazaar-web
  #   ports:
  #   - "8001:8001"
  #   - "8002:8002"
  #   - "8003:8003"
  #   links:
  #     - postgres

  postgres:
    image: postgres:10.5
    container_name: haskell-bazaar-postgres
    volumes:
      - /data/postgresql:/var/lib/postgresql/data

      # Run init.sql and see.sql on startup
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      # - ./scripts/db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=haskellbazaar
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=haskellbazaar
      - POSTGRES_PORT=5432
