name:                haskell-bazaar
version:             0.1.0.0
github:              "chouffe/haskell-bazaar"
license:             BSD3
author:              "Arthur Caillau"
maintainer:          "chouffe.caillau@gmail.com"
copyright:           "2018 Arthur Caillau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-bazaar#readme>

dependencies:
- aeson
- base >= 4.9 && < 5
- bytestring
- containers
- esqueleto
- fast-logger
- http-media
- http-types
- lens
- mtl
- monad-logger
- persistent
- persistent-postgresql
- persistent-template
- resource-pool
- servant
- servant-client
- servant-server
- text
- time
- transformers
- uuid
- wai
- wai-cors
- wai-extra
- warp
- wreq

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  haskell-bazaar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-bazaar

tests:
  haskell-bazaar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-bazaar
    - http-client
    - http-client-tls
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - tasty-hspec
