version: '3'

services:
  web:
    image: haskell-bazaar-server
    container_name: haskell-bazaar-web
    ports:
    - "8001:8001"
    links:
      - postgres
    environment:
      - ENVIRONMENT=Prod

  loadbalancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - web
    ports:
      - "80:80"
